### ISSUE TITLE
Die for-Schleifen müssen nicht durch das ganze Wort laufen

### ISSUE THREAD

**Issue by gossie** [code-bella/Week1-end-of-week-task#2]
Du hast drei Methoden, die eine Prüfung machen, die alle ungefähr so aussehen:
```java
private static Boolean lowercaseLetterChecker(String password) {
    boolean result = false;
    for (int i=0; i < password.length(); i++) {
        if (Character.isLowerCase(password.charAt(i))) {
            result = true;
        }
    }
    return result;
}
```
Sobald die `if`-Abfrage `true` ergibt, musst du aber nicht mehr weitersuchen und könntest `true` zurückgeben.
```java
private static Boolean lowercaseLetterChecker(String password) {
    for (int i=0; i < password.length(); i++) {
        if (Character.isLowerCase(password.charAt(i))) {
            return true;
        }
    }
    return false;
}
```

https://github.com/code-bella/Week1-end-of-week-task/blob/ea5b883e5c1690b9c0075d2e16a72b4171d57655/src/main/java/de/codebella/EndOfWeek1Task.java#L31

https://github.com/code-bella/Week1-end-of-week-task/blob/ea5b883e5c1690b9c0075d2e16a72b4171d57655/src/main/java/de/codebella/EndOfWeek1Task.java#L41

https://github.com/code-bella/Week1-end-of-week-task/blob/ea5b883e5c1690b9c0075d2e16a72b4171d57655/src/main/java/de/codebella/EndOfWeek1Task.java#L51

**Comment by codexbella** [comment]
Ja, ich weiß. Hatte es auch erst so, aber irgendwas war, warum ich auf den Zwischenweg umgestiegen bin. Aber Tests laufen jetzt auch mit direkt "return" gut, also back to basics.
